CREATE TABLE "HotelApp".customer (
"ID" INTEGER PRIMARY KEY,
"username" VARCHAR(10),
"password" VARCHAR(20),
"mail" VARCHAR(20),
"name" VARCHAR(30),
"surname" VARCHAR(30),
"identificationNumber" VARCHAR(20),
"birthDate" VARCHAR(10),
"phone" VARCHAR(15),
"gender" SMALLINT
);

CREATE TABLE "HotelApp".hotel (
"ID" INTEGER PRIMARY KEY,
"name" VARCHAR(30),
"address" TEXT,
"website" VARCHAR(50),
"telNo" VARCHAR(15),
"fax" VARCHAR(15),
"rank" REAL
);

CREATE TABLE "HotelApp".room (
"ID" INTEGER PRIMARY KEY,
"hotelID" INTEGER references "HotelApp".hotel("ID"),
"type" VARCHAR(15),
"isFull" BOOLEAN,
"facilities" TEXT,
"description" TEXT,
"photo" TEXT,
"roomSize" INTEGER,
"currency" VARCHAR(15),
"price" REAL
);

CREATE TABLE "HotelApp".reservation (
"ID" SERIAL PRIMARY KEY,
"customerID" INTEGER references "HotelApp".customer("ID"),
"roomID" INTEGER references "HotelApp".room("ID"),
"hotelID" INTEGER references "HotelApp".hotel("ID"),
"checkInDate" VARCHAR(10),
"checkOutDate" VARCHAR(10)
);

INSERT INTO "HotelApp".customer
("ID", username, "password", mail, "name", surname, "identificationNumber", "birthDate", phone, gender)
VALUES(1, 'alp', '123456', 'alp@alp.com', 'Alp', 'Akosman', '12345678901', '03/03/1998', '+905551234567', 1);

INSERT INTO "HotelApp".hotel
("ID", "name", address, website, "telNo", fax, "rank")
VALUES(1, 'Aparthotel Colombo Roma', 'Via Cristoforo Colombo, 112, 00154 Roma RM, İtalya', 'https://www.aparthotelcolomboroma.it/', '+390698376099', '', 8.8);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(1, 1, 'TwinRoom', false, 
'Desk,
Safety deposit box,
Upper floors accessible by elevator,
Flat-screen TV,
Wake up service/Alarm clock,
Towels,
Socket near the bed,
TV,
Hypoallergenic,
Linen,
Minibar,
Tile/marble floor,
Electric kettle,
Heating,
Wardrobe or closet,
Soundproofing,
Satellite channels,
Air conditioning,
Clothes rack', 
'Offering free toiletries, this double room includes a private bathroom with a shower, a bidet and a hairdryer. The double room offers air conditioning, soundproof walls, a minibar, a wardrobe, as well as a flat-screen TV with satellite channels.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/500109161.jpg?k=245406fb7800972b0d5af0f72ac88264eb7d1ee91d6012d588029f0b5a39adeb&o=',
21, 'TL', 2782);


INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(2, 1, 'Triple', false,
'Kitchenette,
Refrigerator,
Microwave,
Kitchenware,
Minibar,
Electric kettle,
Stovetop,
Dining area,
Dining table,
Desk,
Safety deposit box,
Dining table,
Upper floors accessible by elevator,
Flat-screen TV,
Wake up service/Alarm clock,
Sofa,
Towels,
Socket near the bed,
Microwave,
TV,
Refrigerator,
Hypoallergenic,
Linen,
Minibar,
Stovetop,
Tile/marble floor,
Kitchenware,
Kitchenette,
Electric kettle,
Sofa bed,
Heating,
Wardrobe or closet,
Soundproofing,
Satellite channels,
Air conditioning,
Dining area,
Clothes rack', 
'Providing free toiletries, this studio includes a private bathroom with a shower, a bidet and a hairdryer. In the well-equipped kitchenette, guests will find a stovetop, a refrigerator, kitchenware and a microwave. This air-conditioned studio consists of a dining area, a flat-screen TV with satellite channels soundproof walls and a minibar.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/500962033.jpg?k=4914b8acd074d298ef936fcc9c4f3218d5785628754a61ef364ea98750760f31&o=',
27, 'TL', 4051);


INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(3, 1, 'Quad', false,
'Kitchenette,
Refrigerator,
Microwave,
Kitchenware,
Minibar,
Electric kettle,
Stovetop,
Dining area,
Dining table,
Desk,
Safety deposit box,
Dining table,
Upper floors accessible by elevator,
Flat-screen TV,
Wake up service/Alarm clock,
Sofa,
Towels,
Socket near the bed,
Microwave,
TV,
Refrigerator,
Hypoallergenic,
Linen,
Minibar,
Stovetop,
Tile/marble floor,
Kitchenware,
Kitchenette,
Electric kettle,
Sofa bed,
Heating,
Wardrobe or closet,
Soundproofing,
Satellite channels,
Air conditioning,
Dining area,
Clothes rack', 
'The air-conditioned apartment features 2 bedrooms and 1 bathroom with a shower and a bidet. Guests can make meals in the kitchenette that comes with a stovetop, a refrigerator, kitchenware and a microwave. The apartment provides a flat-screen TV with satellite channels, soundproof walls, a minibar, a seating area as well as city views. The unit offers 4 beds.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/500110067.jpg?k=453d460d9497e7f05c5c54a0c27f7a2ddfd66888b6c5118842d2f161d0bf38a5&o=',
56, 'TL', 6687);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(4, 1, 'OnePersonRoom', false,
'Desk,
Safety deposit box,
Upper floors accessible by elevator,
Flat-screen TV,
Wake up service/Alarm clock,
Towels,
Socket near the bed,
TV,
Hypoallergenic,
Linen,
Minibar,
Tile/marble floor,
Electric kettle,
Heating,
Wardrobe or closet,
Soundproofing,
Satellite channels,
Air conditioning,
Clothes rack', 
'Offering free toiletries, this double room includes a private bathroom with a shower, a bidet and a hairdryer. The double room offers air conditioning, soundproof walls, a minibar, a wardrobe, as well as a flat-screen TV with satellite channels.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/500109165.jpg?k=96bd09ae5614fe30fd5a7871d77ca3a19116e6e6dd58b496a44258309cb8c72a&o=',
21, 'TL', 2620);


INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(5, 1, 'OnePersonRoom', false,
'Desk,
Safety deposit box,
Upper floors accessible by elevator,
Flat-screen TV,
Wake up service/Alarm clock,
Towels,
Socket near the bed,
TV,
Hypoallergenic,
Linen,
Minibar,
Tile/marble floor,
Electric kettle,
Heating,
Wardrobe or closet,
Soundproofing,
Satellite channels,
Air conditioning,
Clothes rack', 
'Offering free toiletries, this double room includes a private bathroom with a shower, a bidet and a hairdryer. The double room offers air conditioning, soundproof walls, a minibar, a wardrobe, as well as a flat-screen TV with satellite channels.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/500109165.jpg?k=96bd09ae5614fe30fd5a7871d77ca3a19116e6e6dd58b496a44258309cb8c72a&o=',
21, 'TL', 2929);

INSERT INTO "HotelApp".hotel
("ID", "name", address, website, "telNo", fax, "rank")
VALUES(2, 'Diros Hotel', 'Agiou Konstantinou 21, Athina 104 31, Yunanistan', 'https://www.diroshotel.eu/', '+302105248112', '', 7.5);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(6, 2, 'OnePersonRoom', false,
'Desk,
TV,
Refrigerator,
Linen,
Tile/marble floor,
Flat-screen TV,
Wake-up service,
Iron,
Heating,
Telephone,
Towels,
Wardrobe or closet,
Socket near the bed,
Air conditioning', 
'Renovated room with air conditioning, free Wi-Fi, LCD TV and private balcony.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/407547459.jpg?k=4473f0ca817035415d8ecfb95ade40c63083073ee7e4a7e75ebe5d88f2d4af44&o=',
16, 'TL', 1136);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(7, 2, 'TwinRoom', false,
'Desk,
TV,
Refrigerator,
Linen,
Tile/marble floor,
Flat-screen TV,
Wake-up service,
Iron,
Heating,
Telephone,
Towels,
Wardrobe or closet,
Socket near the bed,
Air conditioning', 
'Renovated room with air conditioning, free Wi-Fi, LCD TV and private balcony.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/407547459.jpg?k=4473f0ca817035415d8ecfb95ade40c63083073ee7e4a7e75ebe5d88f2d4af44&o=',
16, 'TL', 1461);

INSERT INTO "HotelApp".hotel
("ID", "name", address, website, "telNo", fax, "rank")
VALUES(3, 'Four Seasons Hotel George V', '31 Av. George V, 75008 Paris, Fransa', 'https://www.fourseasons.com/', '+33149527000', '', 9.4);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(8, 3, 'King', false,
'Desk,
Safety deposit box,
Flat-screen TV,
Alarm clock,
Iron,
iPad,
Fan,
Game console – Xbox 360,
DVD player,
Books, DVDs, or music for children,
Ironing facilities,
Video games,
Microwave,
Game console – Nintendo Wii,
Video,
Game console – PS3,
TV,
Hypoallergenic,
Linen,
Tile/marble floor,
Laptop,
Private entrance,
Heating,
Tumble dryer,
Cable channels,
Radio,
Cleaning products,
Game console,
Air conditioning,
Clothes rack,
Coffee machine,
Child safety socket covers,
Upper floors accessible by elevator,
Upper floors accessible by stairs only,
Extra long beds (> 2 metres),
Pay-per-view channels,
Wake-up service,
Wake up service/Alarm clock,
Blu-ray player,
Towels,
Board games/puzzles,
Socket near the bed,
Game console – PS2,
Tea/Coffee maker,
Refrigerator,
Minibar,
Carpeted,
Electric kettle,
Telephone,
Dressing room,
Baby safety gates,
CD player,
Fax,
Wardrobe or closet,
Soundproofing,
Satellite channels,
Interconnected room(s) available,
Childrens high chair,
Hand sanitiser', 
'Airy, gracefully-appointed deluxe rooms boasting crystal chandeliers. Features a marble bathroom with relaxing, soaking tub and separate shower.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/204849808.jpg?k=068be813d5e496a2a27c56d30ae8f83ce0e5ed23fc61a07745a86118e8264ee5&o=',
45, 'TL', 77343);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(9, 3, 'TwinRoom', false,
'Desk,
Safety deposit box,
Flat-screen TV,
Alarm clock,
Iron,
iPad,
Fan,
Game console – Xbox 360,
DVD player,
Books, DVDs, or music for children,
Ironing facilities,
Seating Area,
Fold-up bed,
Video games,
Microwave,
Game console – Nintendo Wii,
Video,
Game console – PS3,
TV,
Hypoallergenic,
Linen,
Tile/marble floor,
Laptop,
Private entrance,
Sofa bed,
Heating,
Tumble dryer,
Cable channels,
Radio,
Cleaning products,
Game console,
Air conditioning,
Clothes rack,
Coffee machine,
Child safety socket covers,
Upper floors accessible by elevator,
Upper floors accessible by stairs only,
Extra long beds (> 2 metres),
Pay-per-view channels,
Wake-up service,
Wake up service/Alarm clock,
Sofa,
Blu-ray player,
Towels,
Board games/puzzles,
Socket near the bed,
Game console – PS2,
Tea/Coffee maker,
Refrigerator,
Minibar,
Carpeted,
Electric kettle,
Telephone,
Baby safety gates,
CD player,
Fax,
Wardrobe or closet,
Soundproofing,
Satellite channels,
Interconnected room(s) available,
Childrens high chair,
Hand sanitise', 
'Airy, gracefully-appointed deluxe rooms boasting crystal chandeliers. Features a marble bathroom with relaxing, soaking tub and separate shower.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/204849808.jpg?k=068be813d5e496a2a27c56d30ae8f83ce0e5ed23fc61a07745a86118e8264ee5&o=',
45, 'TL', 77343);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(10, 3, 'King', false,
'Desk,
Safety deposit box,
Flat-screen TV,
Alarm clock,
Outdoor furniture,
Iron,
iPad,
Fan,
Game console – Xbox 360,
DVD player,
Books, DVDs, or music for children,
Ironing facilities,
Seating Area,
Fold-up bed,
Video games,
Microwave,
Game console – Nintendo Wii,
Video,
Game console – PS3,
TV,
Hypoallergenic,
Linen,
Tile/marble floor,
Laptop,
Private entrance,
Sofa bed,
Heating,
Tumble dryer,
Cable channels,
Radio,
Cleaning products,
Game console,
Air conditioning,
Clothes rack,
Coffee machine,
Child safety socket covers,
Upper floors accessible by elevator,
Upper floors accessible by stairs only,
Extra long beds (> 2 metres),
Pay-per-view channels,
Wake-up service,
Wake up service/Alarm clock,
Sofa,
Blu-ray player,
Towels,
Board games/puzzles,
Socket near the bed,
Game console – PS2,
Tea/Coffee maker,
Refrigerator,
Minibar,
Carpeted,
Electric kettle,
Telephone,
Baby safety gates,
CD player,
Fax,
Wardrobe or closet,
Outdoor dining area,
Soundproofing,
Satellite channels,
Interconnected room(s) available,
Childrens high chair,
Hand sanitiser', 
'Rooms offer views of the Marble Courtyard and the surrounding avenues.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/204846597.jpg?k=842dec2f4c3b158829c35df8ea99607400b1e589a7125c96f8f379518a1d3a3a&o=',
55, 'TL', 105872);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(11, 3, 'King', false,
'Desk,
Safety deposit box,
Flat-screen TV,
Alarm clock,
Outdoor furniture,
Iron,
iPad,
Fan,
Game console – Xbox 360,
DVD player,
Books, DVDs, or music for children,
Ironing facilities,
Seating Area,
Fold-up bed,
Video games,
Microwave,
Game console – Nintendo Wii,
Video,
Game console – PS3,
TV,
Hypoallergenic,
Linen,
Tile/marble floor,
Laptop,
Private entrance,
Sofa bed,
Heating,
Tumble dryer,
Cable channels,
Radio,
Cleaning products,
Game console,
Air conditioning,
Clothes rack,
Coffee machine,
Child safety socket covers,
Upper floors accessible by elevator,
Upper floors accessible by stairs only,
Extra long beds (> 2 metres),
Pay-per-view channels,
Wake-up service,
Wake up service/Alarm clock,
Sofa,
Blu-ray player,
Towels,
Board games/puzzles,
Socket near the bed,
Game console – PS2,
Tea/Coffee maker,
Refrigerator,
Minibar,
Carpeted,
Electric kettle,
Telephone,
Baby safety gates,
CD player,
Fax,
Wardrobe or closet,
Outdoor dining area,
Soundproofing,
Satellite channels,
Interconnected room(s) available,
Childrens high chair,
Hand sanitiser', 
'Rooms offer views of the Marble Courtyard and the surrounding avenues.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/22490656.jpg?k=e7720e45fe0b8c0b8048282bc43a8d9bf1134d648bb05792270610b94e330cac&o=',
55, 'TL', 114117);


INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(12, 3, 'King', false,
'Desk,
Safety deposit box,
Flat-screen TV,
Alarm clock,
Outdoor furniture,
Iron,
iPad,
Fan,
Game console – Xbox 360,
DVD player,
Books, DVDs, or music for children,
Ironing facilities,
Seating Area,
Fold-up bed,
Video games,
Microwave,
Game console – Nintendo Wii,
Video,
Game console – PS3,
TV,
Hypoallergenic,
Linen,
Tile/marble floor,
Laptop,
Private entrance,
Sofa bed,
Heating,
Tumble dryer,
Cable channels,
Radio,
Cleaning products,
Game console,
Air conditioning,
Clothes rack,
Coffee machine,
Child safety socket covers,
Upper floors accessible by elevator,
Upper floors accessible by stairs only,
Extra long beds (> 2 metres),
Pay-per-view channels,
Wake-up service,
Wake up service/Alarm clock,
Sofa,
Blu-ray player,
Towels,
Board games/puzzles,
Socket near the bed,
Game console – PS2,
Tea/Coffee maker,
Refrigerator,
Minibar,
Carpeted,
Electric kettle,
Telephone,
Baby safety gates,
CD player,
Fax,
Wardrobe or closet,
Outdoor dining area,
Soundproofing,
Satellite channels,
Interconnected room(s) available,
Childrens high chair,
Hand sanitiser', 
'Rooms offer views of the Marble Courtyard and the surrounding avenues.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/22490656.jpg?k=e7720e45fe0b8c0b8048282bc43a8d9bf1134d648bb05792270610b94e330cac&o=',
55, 'TL', 114117);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(13, 3, 'King', false,
'Desk,
Safety deposit box,
Flat-screen TV,
Alarm clock,
Iron,
iPad,
Fan,
Game console – Xbox 360,
DVD player,
Books, DVDs, or music for children,
Ironing facilities,
Seating Area,
Fold-up bed,
Video games,
Microwave,
Game console – Nintendo Wii,
Video,
Game console – PS3,
TV,
Hypoallergenic,
Linen,
Tile/marble floor,
Laptop,
Private entrance,
Kitchenware,
Sofa bed,
Heating,
Tumble dryer,
Cable channels,
Radio,
Cleaning products,
Game console,
Air conditioning,
Clothes rack,
Coffee machine,
Child safety socket covers,
Dining table,
Upper floors accessible by elevator,
Upper floors accessible by stairs only,
Extra long beds (> 2 metres),
Pay-per-view channels,
Wake-up service,
Wake up service/Alarm clock,
Sofa,
Blu-ray player,
Towels,
Board games/puzzles,
Socket near the bed,
Game console – PS2,
Tea/Coffee maker,
Refrigerator,
Minibar,
Carpeted,
Kitchenette,
Electric kettle,
Telephone,
Dressing room,
Baby safety gates,
CD player,
Fax,
Wardrobe or closet,
Soundproofing,
Satellite channels,
Interconnected room(s) available,
Childrens high chair,
Dining area,
Hand sanitiser', 
'Featuring a private entrance, this spacious suite also is comprised of 1 bedroom, a seating area and 1 bathroom with a walk-in shower and a bath. Guests can make meals in the kitchenette that comes with a refrigerator, kitchenware and a microwave. The air-conditioned suite offers a flat-screen TV with cable channels, soundproof walls, a minibar, a tea and coffee maker as well as city views. The unit offers 1 bed.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/501826501.jpg?k=bbc7e67e5458df24694aa2665d750bc1a97012f460f278cf5232df021b3d05fe&o=',
110, 'TL', 282985);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(14, 3, 'King', false,
'Desk,
Safety deposit box,
Flat-screen TV,
Alarm clock,
Iron,
iPad,
Fan,
Game console – Xbox 360,
DVD player,
Books, DVDs, or music for children,
Ironing facilities,
Seating Area,
Fold-up bed,
Video games,
Microwave,
Game console – Nintendo Wii,
Video,
Game console – PS3,
TV,
Hypoallergenic,
Linen,
Tile/marble floor,
Laptop,
Private entrance,
Kitchenware,
Sofa bed,
Heating,
Tumble dryer,
Cable channels,
Radio,
Cleaning products,
Game console,
Air conditioning,
Clothes rack,
Coffee machine,
Child safety socket covers,
Dining table,
Upper floors accessible by elevator,
Upper floors accessible by stairs only,
Extra long beds (> 2 metres),
Pay-per-view channels,
Wake-up service,
Wake up service/Alarm clock,
Sofa,
Blu-ray player,
Towels,
Board games/puzzles,
Socket near the bed,
Game console – PS2,
Tea/Coffee maker,
Refrigerator,
Minibar,
Carpeted,
Kitchenette,
Electric kettle,
Telephone,
Dressing room,
Baby safety gates,
CD player,
Fax,
Wardrobe or closet,
Soundproofing,
Satellite channels,
Interconnected room(s) available,
Childrens high chair,
Dining area,
Hand sanitiser', 
'Featuring a private entrance, this spacious suite also is comprised of 1 bedroom, a seating area and 1 bathroom with a walk-in shower and a bath. Guests can make meals in the kitchenette that comes with a refrigerator, kitchenware and a microwave. The air-conditioned suite offers a flat-screen TV with cable channels, soundproof walls, a minibar, a tea and coffee maker as well as city views. The unit offers 1 bed.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/501826678.jpg?k=e301641dbf365415b1c7fb920242324ef22a93fb7e76aa8c6dcee6179c1efb66&o=',
110, 'TL', 282985);


INSERT INTO "HotelApp".hotel
("ID", "name", address, website, "telNo", fax, "rank")
VALUES(4, 'Bulgari Hotel Paris', '30 Av. George V, 75008 Paris, Fransa', 'https://www.bulgarihotels.com/paris', '+33181721000', '', 9.6);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(15, 4, 'TwinRoom', false,
'Laptop safe,
Carbon monoxide detector,
Coffee machine,
Safety deposit box,
Hardwood or parquet floors,
Upper floors accessible by elevator,
Flat-screen TV,
Pay-per-view channels,
Wake-up service,
Sofa,
Towels,
Entire unit wheelchair accessible,
Board games/puzzles,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Minibar,
Carpeted,
Heating,
Telephone,
Dressing room,
Wardrobe or closet,
Radio,
Soundproofing,
Interconnected room(s) available,
Satellite channels,
Air conditioning,
Hand sanitiser', 
'The spacious twin/double room provides air conditioning, soundproof walls, as well as a private bathroom featuring a walk-in shower and a bath. The twin/double room features a minibar, a tea and coffee maker, a wardrobe, a safe deposit box and a flat-screen TV with satellite channels.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/490692333.jpg?k=81febc700672c74a40c61a83d741cc8665c74ca7a2b51851729db63c2287afc9&o=',
42, 'TL', 65964);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(16, 4, 'TwinRoom', false,
'Laptop safe,
Carbon monoxide detector,
Coffee machine,
Safety deposit box,
Hardwood or parquet floors,
Upper floors accessible by elevator,
Flat-screen TV,
Pay-per-view channels,
Wake-up service,
Sofa,
Towels,
Entire unit wheelchair accessible,
Board games/puzzles,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Minibar,
Carpeted,
Heating,
Telephone,
Dressing room,
Wardrobe or closet,
Radio,
Soundproofing,
Interconnected room(s) available,
Satellite channels,
Air conditioning,
Hand sanitiser', 
'The spacious twin/double room provides air conditioning, soundproof walls, as well as a private bathroom featuring a walk-in shower and a bath. The twin/double room features a minibar, a tea and coffee maker, a wardrobe, a safe deposit box and a flat-screen TV with satellite channels.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/491141523.jpg?k=83cc6b06d5dc843a590a4c30bea0c3f5d27d81846d7d9ea85b193931efb8c982&o=',
42, 'TL', 65964);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(17, 4, 'TwinRoom', false,
'Laptop safe,
Carbon monoxide detector,
Coffee machine,
Safety deposit box,
Hardwood or parquet floors,
Upper floors accessible by elevator,
Flat-screen TV,
Pay-per-view channels,
Wake-up service,
Sofa,
Towels,
Entire unit wheelchair accessible,
Board games/puzzles,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Minibar,
Carpeted,
Heating,
Telephone,
Dressing room,
Wardrobe or closet,
Radio,
Soundproofing,
Interconnected room(s) available,
Satellite channels,
Air conditioning,
Hand sanitiser', 
'The spacious twin/double room provides air conditioning, soundproof walls, as well as a private bathroom featuring a walk-in shower and a bath. The twin/double room features a minibar, a tea and coffee maker, a wardrobe, a safe deposit box and a flat-screen TV with satellite channels.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/491401798.jpg?k=314a6c5cad4a60637ad358c48839c4d26c95159d4abdc7dcf8dd3b511f0aaffd&o=',
42, 'TL', 65964);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(18, 4, 'TwinRoom', false,
'Laptop safe,
Carbon monoxide detector,
Coffee machine,
Safety deposit box,
Hardwood or parquet floors,
Upper floors accessible by elevator,
Flat-screen TV,
Pay-per-view channels,
Wake-up service,
Sofa,
Towels,
Entire unit wheelchair accessible,
Board games/puzzles,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Minibar,
Carpeted,
Heating,
Telephone,
Dressing room,
Wardrobe or closet,
Radio,
Soundproofing,
Interconnected room(s) available,
Satellite channels,
Air conditioning,
Hand sanitiser', 
'The spacious twin/double room provides air conditioning, soundproof walls, as well as a private bathroom featuring a walk-in shower and a bath. The twin/double room features a minibar, a tea and coffee maker, a wardrobe, a safe deposit box and a flat-screen TV with satellite channels.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/490692339.jpg?k=bb9202b811a7f7f7048e514bf4d9e8f34bb70f1eac508142a2dc4f61f12c71b8&o=',
42, 'TL', 75858);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(19, 4, 'TwinRoom', false,
'Laptop safe,
Carbon monoxide detector,
Coffee machine,
Safety deposit box,
Hardwood or parquet floors,
Upper floors accessible by elevator,
Flat-screen TV,
Pay-per-view channels,
Wake-up service,
Sofa,
Towels,
Entire unit wheelchair accessible,
Board games/puzzles,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Minibar,
Carpeted,
Heating,
Telephone,
Dressing room,
Wardrobe or closet,
Radio,
Soundproofing,
Interconnected room(s) available,
Satellite channels,
Air conditioning,
Hand sanitiser', 
'The spacious twin/double room provides air conditioning, soundproof walls, as well as a private bathroom featuring a walk-in shower and a bath. The twin/double room features a minibar, a tea and coffee maker, a wardrobe, a safe deposit box and a flat-screen TV with satellite channels.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/490692996.jpg?k=594d15e3d2a83c34c4a4d6e90276cec9a391d18b07e751c3de7b43db96a27ffe&o=',
42, 'TL', 75858);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(20, 4, 'TwinRoom', false,
'Laptop safe,
Carbon monoxide detector,
Coffee machine,
Safety deposit box,
Hardwood or parquet floors,
Upper floors accessible by elevator,
Flat-screen TV,
Pay-per-view channels,
Wake-up service,
Sofa,
Towels,
Entire unit wheelchair accessible,
Board games/puzzles,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Minibar,
Carpeted,
Heating,
Telephone,
Dressing room,
Wardrobe or closet,
Radio,
Soundproofing,
Interconnected room(s) available,
Satellite channels,
Air conditioning,
Hand sanitiser', 
'The spacious twin/double room provides air conditioning, soundproof walls, as well as a private bathroom featuring a walk-in shower and a bath. The twin/double room features a minibar, a tea and coffee maker, a wardrobe, a safe deposit box and a flat-screen TV with satellite channels.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/491141544.jpg?k=9d99b000ca6ca13de21613e13987fc73af2837eb9b409e136cb4622acb6ac861&o=',
42, 'TL', 75858);


INSERT INTO "HotelApp".hotel
("ID", "name", address, website, "telNo", fax, "rank")
VALUES(5, 'Hôtel Avenir-Jonquière', '23 Rue de La Jonquière, 75017 Paris, Fransa', 'https://www.hotelavenirjonquiere.eu/', '+33146278341', '', 7.9);


INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(21, 5, 'TwinRoom', false,
'TV,
Linen,
Hardwood or parquet floors,
Upper floors accessible by stairs only,
Flat-screen TV,
Heating,
Dressing room,
Towels,
Wardrobe or closet,
Soundproofing,
Socket near the bed', 
'This double room has soundproofing.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/48655644.jpg?k=bdb532a1dd4edece1b57ef75479537b0728b142261535336bb1ee1c7328993bc&o=',
12, 'TL', 2606);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(22, 5, 'TwinRoom', false,
'TV,
Linen,
Hardwood or parquet floors,
Upper floors accessible by stairs only,
Flat-screen TV,
Heating,
Dressing room,
Towels,
Wardrobe or closet,
Soundproofing,
Socket near the bed', 
'This double room has soundproofing.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/48655621.jpg?k=ba3af4eeb26ad8d6d5c68c62031c4dea2fbd21ea60ab98b31c57f9e287b958c8&o=',
12, 'TL', 2606);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(23, 5, 'TwinRoom', false,
'TV,
Linen,
Hardwood or parquet floors,
Upper floors accessible by stairs only,
Flat-screen TV,
Heating,
Dressing room,
Towels,
Wardrobe or closet,
Soundproofing,
Socket near the bed', 
'This double room has soundproofing.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/48655626.jpg?k=a6764934292456e91fbd696a264f645667fa6857b70dd6a5a96d36ab5883553a&o=',
12, 'TL', 2606);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(24, 5, 'TwinRoom', false,
'TV,
Linen,
Hardwood or parquet floors,
Upper floors accessible by stairs only,
Flat-screen TV,
Heating,
Dressing room,
Towels,
Wardrobe or closet,
Soundproofing,
Socket near the bed', 
'This double room has soundproofing.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/48655641.jpg?k=a9ec7b1278418585d9c910a6ecb5e6a75c3161eee268c7932902d1d5b3e73bf2&o=',
12, 'TL', 2606);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(25, 5, 'OnePersonRoom', false,
'TV,
Linen,
Hardwood or parquet floors,
Upper floors accessible by stairs only,
Flat-screen TV,
Heating,
Dressing room,
Towels,
Wardrobe or closet,
Soundproofing,
Socket near the bed', 
'This double room has soundproofing.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/71246512.jpg?k=3b629698ad1ebf994926df8b6999e4e4a1aefa16bc97d841f42885c67dc15300&o=',
9, 'TL', 2276);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(26, 5, 'OnePersonRoom', false,
'TV,
Linen,
Hardwood or parquet floors,
Upper floors accessible by stairs only,
Flat-screen TV,
Heating,
Dressing room,
Towels,
Wardrobe or closet,
Soundproofing,
Socket near the bed', 
'This double room has soundproofing.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/71247091.jpg?k=742c3ce730b92e8b372bb313a0f5d2d1ee8138f508e49e87a6ffce20d40e65ed&o=',
9, 'TL', 2276);

INSERT INTO "HotelApp".hotel
("ID", "name", address, website, "telNo", fax, "rank")
VALUES(6, 'Hotel Calisto', 'Haarlemmerdijk 61, 1013 KB Amsterdam, Hollanda', 'http://www.calistoamsterdam.nl/', '', '', 7.9);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(27, 6, 'TwinRoom', false,
'Linens,
Safe,
Upper floors accessible by stairs only,
Carpeted,
Private entrance,
Heating,
Towels,
Clothes rack', 
'Offering free toiletries, this double room includes a private bathroom with a walk-in shower and a hairdryer. The double room has carpeted floors and offers a private entrance, a safe deposit box and city views. The unit has 1 bed.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/494673470.jpg?k=46ec77ceb5ce3f67d1a5a26aea5338ecc5f958b66d01c7ee4d12a9a7342b3d94&o=',
8, 'TL', 3055);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(28, 6, 'TwinRoom', false,
'Linens,
Safe,
Upper floors accessible by stairs only,
Carpeted,
Private entrance,
Heating,
Towels,
Clothes rack', 
'Offering free toiletries, this double room includes a private bathroom with a walk-in shower and a hairdryer. The double room has carpeted floors and offers a private entrance, a safe deposit box and city views. The unit has 1 bed.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/504712034.jpg?k=1868648fcf2bca8cc43facf469d699f74028cb43980039cc811b49ee5f6161b0&o=',
8, 'TL', 3216);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(29, 6, 'TwinRoom', false,
'Linens,
Safe,
Upper floors accessible by stairs only,
Carpeted,
Private entrance,
Heating,
Towels,
Clothes rack', 
'Offering free toiletries, this double room includes a private bathroom with a walk-in shower and a hairdryer. The double room has carpeted floors and offers a private entrance, a safe deposit box and city views. The unit has 1 bed.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/486318791.jpg?k=7f68cf932798b58d4ee6c17a72d7a955c87461b97931038195a8ef2fdee81233&o=',
10, 'TL', 3216);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(30, 6, 'TwinRoom', false,
'Linens,
Safe,
Upper floors accessible by stairs only,
Carpeted,
Private entrance,
Heating,
Towels,
Clothes rack', 
'Offering free toiletries, this double room includes a private bathroom with a walk-in shower and a hairdryer. The double room has carpeted floors and offers a private entrance, a safe deposit box and city views. The unit has 1 bed.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/508363260.jpg?k=ea10dc9c9243e0ea4bdf2c5348be710bf9ba9b08d92752e96914aa896fc7017d&o=',
10, 'TL', 3216);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(31, 6, 'TwinRoom', false,
'Linens,
Safe,
Upper floors accessible by stairs only,
Carpeted,
Private entrance,
Heating,
Towels,
Wardrobe or closet,
Clothes rack', 
'Our Large Double Room offers spacious comfort within our historic Amsterdam building. Relax in style on the plush Coco Mat bed with a private bathroom and quality linens. Located in the lively Haarlemmerdijk area, youll have easy access to boutique shopping and the citys vibrant atmosphere.
Please note that due to the hotels unique location, steep staircases provide access to all rooms.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/486314242.jpg?k=a4a96e6a0d7c1dea93d5dbc35204eeaebddba2dbe890c4d4c669b94aa1b0ae48&o=',
12, 'TL', 3971);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(32, 6, 'TwinRoom', false,
'Linens,
Safe,
Upper floors accessible by stairs only,
Carpeted,
Private entrance,
Heating,
Towels,
Wardrobe or closet,
Clothes rack', 
'Our Large Double Room offers spacious comfort within our historic Amsterdam building. Relax in style on the plush Coco Mat bed with a private bathroom and quality linens. Located in the lively Haarlemmerdijk area, youll have easy access to boutique shopping and the citys vibrant atmosphere.
Please note that due to the hotels unique location, steep staircases provide access to all rooms.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/483581724.jpg?k=2d691e01ad2cdbd21ecf5acf0805b3155de5cac3d2725c07ef64e02a7a20fb77&o=',
12, 'TL', 4180);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(33, 6, 'TwinRoom', false,
'Linens,
Safe,
Upper floors accessible by stairs only,
Carpeted,
Private entrance,
Heating,
Towels,
Wardrobe or closet,
Clothes rack', 
'Offering free toiletries, this double room includes a private bathroom with a walk-in shower and a hairdryer. Among the room amenities are a private entrance, a wardrobe and a safe deposit box as well as city views. The unit offers 1 bed.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/486343804.jpg?k=77b35c54322df6e5d8b9d8c797645f281399a517ad9f91896076518d61d9a476&o=',
14, 'TL', 4257);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(34, 6, 'TwinRoom', false,
'Linens,
Safe,
Upper floors accessible by stairs only,
Carpeted,
Private entrance,
Heating,
Towels,
Wardrobe or closet,
Clothes rack', 
'Offering free toiletries, this double room includes a private bathroom with a walk-in shower and a hairdryer. Among the room amenities are a private entrance, a wardrobe and a safe deposit box as well as city views. The unit offers 1 bed.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/486310938.jpg?k=e7c52268ebcfa8fa6017eaa35c22b33e22800d30500c747e1b68abd5dafc756c&o=',
14, 'TL', 4481);


INSERT INTO "HotelApp".hotel
("ID", "name", address, website, "telNo", fax, "rank")
VALUES(7, 'Hampton by Hilton Berlin City', 'Otto-Braun-Straße 69, 10178 Berlin, Almanya', 'https://www.hilton.com/en/hotels/', '+493021308555', '', 8.1);


INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(35, 7, 'TwinRoom', false,
'Laptop safe,
Desk,
Safe,
Upper floors accessible by elevator,
Flat-screen TV,
Wake-up service,
Wake-up service/Alarm clock,
Alarm clock,
Iron,
Towels,
Ironing facilities,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Linens,
Carpeted,
Electric kettle,
Single-room AC for guest accommodation,
Heating,
Telephone,
Wardrobe or closet,
Radio,
Soundproof,
Satellite channels,
Air conditioning,
Clothes rack', 
'Contemporary-style room with an own-brand bed, a 55-inch flat-screen TV, armchair, large desk and tea/coffee facilities.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/484087783.jpg?k=d8701a4ffdfb9bf9f96fcb68e761580d381c5b6a1235e05e4a6f776d044c548f&o=',
19, 'TL', 4502);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(36, 7, 'TwinRoom', false,
'Laptop safe,
Desk,
Safe,
Upper floors accessible by elevator,
Flat-screen TV,
Wake-up service,
Wake-up service/Alarm clock,
Alarm clock,
Iron,
Towels,
Ironing facilities,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Linens,
Carpeted,
Electric kettle,
Single-room AC for guest accommodation,
Heating,
Telephone,
Wardrobe or closet,
Radio,
Soundproof,
Satellite channels,
Air conditioning,
Clothes rack', 
'Contemporary-style room with an own-brand bed, a 55-inch flat-screen TV, armchair, large desk and tea/coffee facilities.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/489667441.jpg?k=a5b746cde959afd172cb0d43a6a4758b7120a8279b0629537fca143aaaf42dd0&o=',
19, 'TL', 4156);


INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(37, 7, 'TwinRoom', false,
'Laptop safe,
Desk,
Safe,
Upper floors accessible by elevator,
Flat-screen TV,
Wake-up service,
Wake-up service/Alarm clock,
Alarm clock,
Iron,
Towels,
Ironing facilities,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Linens,
Carpeted,
Electric kettle,
Single-room AC for guest accommodation,
Heating,
Telephone,
Wardrobe or closet,
Radio,
Soundproof,
Interconnecting room(s) available,
Satellite channels,
Air conditioning,
Clothes rack', 
'Contemporary-style room with an own-brand bed, a 55-inch flat-screen TV, armchair, large desk and tea/coffee facilities.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/484087775.jpg?k=805a08111a89a2b15e99739249d82a3667c7ea7f3a891650de075cbce555a81d&o=',
19, 'TL', 4502);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(38, 7, 'TwinRoom', false,
'Laptop safe,
Desk,
Safe,
Upper floors accessible by elevator,
Flat-screen TV,
Wake-up service,
Wake-up service/Alarm clock,
Alarm clock,
Iron,
Towels,
Ironing facilities,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Linens,
Carpeted,
Electric kettle,
Single-room AC for guest accommodation,
Heating,
Telephone,
Wardrobe or closet,
Radio,
Soundproof,
Interconnecting room(s) available,
Satellite channels,
Air conditioning,
Clothes rack', 
'Contemporary-style room with an own-brand bed, a 55-inch flat-screen TV, armchair, large desk and tea/coffee facilities.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/489667996.jpg?k=1550d6e5974ebc8188e37d7b524d72287a23af13e082c31b923bdccfd7a101c6&o=',
19, 'TL', 4156);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(39, 7, 'Triple', false,
'Laptop safe,
Desk,
Safe,
Upper floors accessible by elevator,
Flat-screen TV,
Wake-up service,
Wake-up service/Alarm clock,
Alarm clock,
Iron,
Towels,
Entire unit wheelchair accessible,
Ironing facilities,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Linens,
Carpeted,
Electric kettle,
Single-room AC for guest accommodation,
Heating,
Telephone,
Wardrobe or closet,
Radio,
Soundproof,
Interconnecting room(s) available,
Satellite channels,
Air conditioning,
Clothes rack', 
'Contemporary-style room with an own-brand bed, a 55-inch flat-screen TV, armchair, large desk and tea/coffee facilities.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/484087766.jpg?k=d825112178a52db342820f6fc5e36af788bf8197825ec20de42a230489631d08&o=',
20, 'TL', 4848);

INSERT INTO "HotelApp".room
("ID", "hotelID", "type", "isFull", facilities, description, photo, "roomSize", currency, price)
VALUES(40, 7, 'Triple', false,
'Laptop safe,
Desk,
Safe,
Upper floors accessible by elevator,
Flat-screen TV,
Wake-up service,
Wake-up service/Alarm clock,
Sofa,
Alarm clock,
Iron,
Towels,
Ironing facilities,
Sitting area,
Socket near the bed,
Tea/Coffee maker,
TV,
Hypoallergenic,
Linens,
Carpeted,
Electric kettle,
Sofa bed,
Single-room AC for guest accommodation,
Heating,
Telephone,
Wardrobe or closet,
Radio,
Soundproof,
Interconnecting room(s) available,
Satellite channels,
Air conditioning,
Clothes rack', 
'Contemporary-style room with an own-brand bed, a 55-inch flat-screen TV, armchair, large desk and tea/coffee facilities.',
'https://cf.bstatic.com/xdata/images/hotel/max1024x768/489667883.jpg?k=92202b0e77620b88a20516c26ee9d7b6125462d1f5f81d009ca0443f93f14b9a&o=',
20, 'TL', 6580);
